[tool.pdm]
[tool.pdm.dev-dependencies]
lint = [
    "ruff>=0.0.258",
    "black>=23.1.0",
]

[project]
name = "ipyobsplot"
version = "0.1.0"
description = ""
authors = [
    {name = "Julien Barnier", email = "julien@nozav.org"},
]
dependencies = [
    "anywidget>=0.2.0",
    "watchfiles>=0.18.1",
    "pandas>=1.5.3",
    "polars>=0.16.14",
]
requires-python = ">=3.10"
readme = "README.md"
license = {text = "MIT"}

[build-system]
requires = ["pdm-pep517>=1.0"]
build-backend = "pdm.pep517.api"
