[tool.poetry]
name = "pyobsplot"
version = "0.3.0"
description = "Observable Plot in Jupyter notebooks and Quarto documents"
authors = ["Julien Barnier <julien@nozav.org>"]
license = "MIT"
readme = "README.md"
include = ["src/pyobsplot/static/*"]
homepage = "https://github.com/juba/pyobsplot"
documentation = "https://juba.github.io/pyobsplot"
repository = "https://github.com/juba/pyobsplot"
changelog = "https://github.com/juba/pyobsplot/blob/main/NEWS.md"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Framework :: Jupyter :: JupyterLab",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: JavaScript",
    "Topic :: Scientific/Engineering :: Visualization"
]



[tool.poetry.dependencies]
python = "^3.8"
anywidget = {extras = ["dev"], version = "^0.2.0"}
pandas = ">=1.2.0"
polars = ">=0.16.0"
pyarrow = "^11.0.0"
ipywidgets = ">=8.0.0"
jupyterlab = ">=3.6.0"

[tool.poetry.group.dev.dependencies]
ruff = "^0.0.259"
black = "^23.1.0"
pytest = "^7.2.2"
requests = "^2.28.2"
topojson = "^1.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
testpaths = "tests"
pythonpath = "src"
