project:
  type: website

execute:
  freeze: auto

website:
  title: "pyobsplot"
  site-url: "https://juba.github.io/pyobsplot"
  favicon: favicon.png
  repo-url: https://github.com/juba/pyobsplot/
  repo-subdir: "doc"
  repo-actions: [issue]
  search:
    location: navbar
    type: overlay
  navbar:
    background: "#e15759"
    pinned: false
    left:
      - getting_started.qmd
      - usage.qmd
      - text: "Gallery"
        menu:
          - gallery_marks.qmd
          - gallery_transforms.qmd
          - gallery_geo.qmd
      - development.qmd
      - changelog.md
    tools:
      - icon: github
        href: https://github.com/juba/pyobsplot/

format:
  html:
    theme: 
      - cosmo
      - custom.scss
    mainfont: "'Source Sans 3', 'Source Sans Pro', 'Segoe UI', 'Roboto', 'Helvetica', sans-serif"
    monofont: "Fira Mono"
    linkcolor: "#FF4222"
    toc: true
    highlight-style: gruvbox
    grid: 
      body-width: 900px
      gutter-width: 3rem



