on:
  workflow_dispatch:
  push:
    branches: [main]

name: Documentation

jobs:
  Build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out pyobsplot-js repository
        uses: actions/checkout@v3
        with:
          repository: juba/pyobsplot-js
          path: "../pyobsplot-js"

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          cache: "npm"

      - name: Install node dependencies
        run: npm install --production=false

      - name: Install poetry
        run: pipx install poetry

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "poetry"

      - name: Bundle
        run: npm run bundle

      - name: Install Python dependencies
        run: poetry install

      - name: Render and Publish
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "julien@nozav.org"
          git config --global user.name "Julien Barnier"
          poetry run quarto publish gh-pages doc
