on:
  workflow_dispatch:
  push:
    branches: [main]

name: Tests

jobs:
  Python-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:

      - name: Check out pyobsplot repository
        uses: actions/checkout@v3
        with:
          path: "pyobsplot"

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          cache: "npm"
          cache-dependency-path: "packages/*/package-lock.json"
            
      - name: Install node dependencies
        run: npm ci

      - name: Install node packages dependencies
        run: npm ci --workspaces

                  
      - name: Install poetry
        run: pipx install poetry

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry"

      - name: Install Python dependencies
        run: cd $GITHUB_WORKSPACE/pyobsplot && poetry install

      - name: Run pytest
        run: cd $GITHUB_WORKSPACE/pyobsplot && poetry run pytest

  JS-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          cache: "npm"
          cache-dependency-path: "packages/*/package-lock.json"          

      - name: Install node dependencies
        run: npm ci --workspaces

      - name: Run tests
        run: npm run test --workspaces


