on:
  workflow_dispatch:
  push:
    branches: [main]

name: Tests

jobs:
  Python-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
      - name: Check out pyobsplot repository
        uses: actions/checkout@v3
        with:
          path: "pyobsplot"

      - name: Check out pyobsplot-js repository
        uses: actions/checkout@v3
        with:
          repository: juba/pyobsplot-js
          path: "pyobsplot-js"
          
      - name: Move to pyobsplot folder
        run: cd pyobsplot

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          cache: "npm"
          
      - name: Install poetry
        run: pipx install poetry

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry"

      - name: Install node dependencies
        run: npm install --production=false

      - name: Install Python dependencies
        run: poetry install

      - name: Run pytest
        run: poetry run pytest

